### ISSUE TITLE
This pulled Marlin version from Marlin Dev branch does not compile

### ISSUE THREAD

**Issue by paulusjacobus** [paulusjacobus/CompileIssue#1]
@wackerbarth I have created this branch for you to test if it compiles on your system.

Thanks heaps Paul

**Comment by AnHardt** [comment]
File `configuration_store.cpp` is not in your reposity. Deleted?
Exactly there are the functions the linker can't find.

**Comment by paulusjacobus** [comment]
Thanks @anhardt i must have lost it when moving files from my dropbox to my laptop. I will recompile it tomorrow and do some more testing.

**Comment by paulusjacobus** [comment]
Create a branch rather than uploading a repo so it becomes obvious when a file is missing
